devMode: true

service:
  serverPort: "8888"

mysqlServer:
  address: "127.0.0.1:3306"
  userName: "root"
  passWord: "123456"
  mysqlMaxDBs: 30
  defaultDbName: "huxiang"

redisServer:
  address: "127.0.0.1:6379"
  passWord: "123456"

esServer:
  esHosts: "http://127.0.0.1:9200"
  esUser: ""
  esPassword: ""

kafka:
  brokers: "172.21.05:9092"
  consumerGroupID: "huxiang"
  goroutineCount: 20
  producer:
    topic: "huxiang"
  comsumer:
    topic: "huxiang"

