devMode: true

service:
  serverPort: "8888"

mysqlServer:
  address: "127.0.0.1:6379"
  userName: "root"
  passWord: "123456"
  mysqlMaxDBs: 30
  defaultDbName: "huxiang"

redisServer:
  addres: "127.0.0.1"
  redisPassword: "123456"

esServer:
  hosts: "http://127.0.0.1:9200"
  esUser: ""
  esPassword: ""
