devMode: true

service:
  serverPort: "8080"

mysqlServer:
  address: "127.0.0.1"
  userName: "root"
  passWord: "123456"
  mysqlMaxDBs: 30
  defaultDbName: "huxiang"

redisServer:
  addres: "127.0.0.1"
  redisPassword: "123456"