devMode: true

service:
  serverPort: "8888"

logger:
  level: 0  # 0（debug以及以上） 1(info以及以上) 2(warn) 3 error
  logDir: './logs'
  fileTimeFormat: "2006-01-02-15" # 日期时间切割go-format格式
  maxSizeM: 4096  # 单日志文件最大大小（MB）
  rotateMaxAge: 10 # 日志文件最大保存天数 超过会删除

mysqlServer:
  address: "127.0.0.1:3306"
  userName: "root"
  passWord: "123456"
  mysqlMaxDBs: 30
  defaultDbName: "huxiang"

redisServer:
  address: "127.0.0.1:6379"
  passWord: "123456"

esServer:
  esHosts: "http://127.0.0.1:9200"
  esUser: ""
  esPassword: ""

kafka:
  brokers: "172.21.05:9092"
  consumerGroupID: "huxiang"
  goroutineCount: 20
  producer:
    topic: "huxiang"
  comsumer:
    topic: "huxiang"

