// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.0
// source: goFix.proto

//path 表示生成的go文件的存放地址，会自动生成目录的。
//name 表示生成的go文件所属的包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfoAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Sex      int64  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *UserInfoAPI) Reset() {
	*x = UserInfoAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goFix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoAPI) ProtoMessage() {}

func (x *UserInfoAPI) ProtoReflect() protoreflect.Message {
	mi := &file_goFix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoAPI.ProtoReflect.Descriptor instead.
func (*UserInfoAPI) Descriptor() ([]byte, []int) {
	return file_goFix_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoAPI) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfoAPI) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoAPI) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfoAPI) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfoAPI) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserInfoREPLY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserInfoREPLY) Reset() {
	*x = UserInfoREPLY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goFix_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoREPLY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoREPLY) ProtoMessage() {}

func (x *UserInfoREPLY) ProtoReflect() protoreflect.Message {
	mi := &file_goFix_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoREPLY.ProtoReflect.Descriptor instead.
func (*UserInfoREPLY) Descriptor() ([]byte, []int) {
	return file_goFix_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoREPLY) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserInfoREPLY) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_goFix_proto protoreflect.FileDescriptor

var file_goFix_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x46, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x81, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x50,
	0x49, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x3d, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x45, 0x50, 0x4c, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goFix_proto_rawDescOnce sync.Once
	file_goFix_proto_rawDescData = file_goFix_proto_rawDesc
)

func file_goFix_proto_rawDescGZIP() []byte {
	file_goFix_proto_rawDescOnce.Do(func() {
		file_goFix_proto_rawDescData = protoimpl.X.CompressGZIP(file_goFix_proto_rawDescData)
	})
	return file_goFix_proto_rawDescData
}

var file_goFix_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_goFix_proto_goTypes = []interface{}{
	(*UserInfoAPI)(nil),   // 0: pb.UserInfoAPI
	(*UserInfoREPLY)(nil), // 1: pb.UserInfoREPLY
}
var file_goFix_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goFix_proto_init() }
func file_goFix_proto_init() {
	if File_goFix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goFix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goFix_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoREPLY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goFix_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goFix_proto_goTypes,
		DependencyIndexes: file_goFix_proto_depIdxs,
		MessageInfos:      file_goFix_proto_msgTypes,
	}.Build()
	File_goFix_proto = out.File
	file_goFix_proto_rawDesc = nil
	file_goFix_proto_goTypes = nil
	file_goFix_proto_depIdxs = nil
}
